# Generated by Django 4.1.3 on 2022-12-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startujemy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mpk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='mpk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startujemy.mpk'),
        ),
    ]
