# Generated by Django 4.1.3 on 2022-12-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startujemy', '0003_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='manager_wmb',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='startujemy.manager'),
            preserve_default=False,
        ),
    ]
