# Generated by Django 4.1.3 on 2022-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startujemy', '0005_alter_manager_options_alter_mpk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='sn_computer',
            field=models.CharField(default=0, max_length=30, verbose_name='Komputer wagowy (S/N)'),
            preserve_default=False,
        ),
    ]
